name: Awesome Telegram Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for opening this issue, we will get back to you shortly!"
        pr-message: "Thanks for opening this pull request! we would appreciate it if you would update some of our documentation based on your changes."
